
#line 3 "lex.xx.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer xx_create_buffer
#define yy_delete_buffer xx_delete_buffer
#define yy_flex_debug xx_flex_debug
#define yy_init_buffer xx_init_buffer
#define yy_flush_buffer xx_flush_buffer
#define yy_load_buffer_state xx_load_buffer_state
#define yy_switch_to_buffer xx_switch_to_buffer
#define yyin xxin
#define yyleng xxleng
#define yylex xxlex
#define yylineno xxlineno
#define yyout xxout
#define yyrestart xxrestart
#define yytext xxtext
#define yywrap xxwrap
#define yyalloc xxalloc
#define yyrealloc xxrealloc
#define yyfree xxfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE xxrestart(xxin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int xxleng;

extern FILE *xxin, *xxout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up xxtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up xxtext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via xxrestart()), so that the user can continue scanning by
	 * just pointing xxin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when xxtext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int xxleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow xxwrap()'s to do buffer switches
 * instead of setting up a fresh xxin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void xxrestart (FILE *input_file  );
void xx_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE xx_create_buffer (FILE *file,int size  );
void xx_delete_buffer (YY_BUFFER_STATE b  );
void xx_flush_buffer (YY_BUFFER_STATE b  );
void xxpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void xxpop_buffer_state (void );

static void xxensure_buffer_stack (void );
static void xx_load_buffer_state (void );
static void xx_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER xx_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE xx_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE xx_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE xx_scan_bytes (yyconst char *bytes,int len  );

void *xxalloc (yy_size_t  );
void *xxrealloc (void *,yy_size_t  );
void xxfree (void *  );

#define yy_new_buffer xx_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        xxensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            xx_create_buffer(xxin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        xxensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            xx_create_buffer(xxin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *xxin = (FILE *) 0, *xxout = (FILE *) 0;

typedef int yy_state_type;

extern int xxlineno;

int xxlineno = 1;

extern char *xxtext;
#define yytext_ptr xxtext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up xxtext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	xxleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 14
#define YY_END_OF_BUFFER 15
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[176] =
    {   0,
       12,   12,   15,   12,   13,   12,   12,   12,   12,   12,
       12,   12,   12,   12,    2,    1,   13,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,    3,   12,   12,   12,   12,
       12,   12,   12,   12,   11,   12,   12,   12,    5,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        4,   12,   12,    7,    8,   12,   12,   12,   12,   10,
       12,   12,   12,   12,   12,    7,    7,    7,    8,    8,
        8,    8,   12,   12,    6,   12,   12,   12,   12,   12,

       12,   12,    7,    7,    8,    8,   12,   12,   12,   12,
       12,   12,   12,    7,    8,   12,   12,   12,   12,   12,
       12,    7,    8,   12,    9,   12,   12,   12,   12,    7,
        8,   12,    9,   12,   12,   12,   12,    7,    8,   12,
       12,   12,   12,    9,    7,    8,   12,   12,    9,   12,
        9,    3,    7,    8,   12,   12,    9,    9,    9,    7,
        8,   12,    9,    9,    4,    7,    8,    9,    9,    9,
        7,    8,    9,    6,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    6,    1,    1,
        7,    1,    1,    1,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        1,    1,    1,    1,    9,    1,   10,    8,   11,   12,

       13,   14,    8,   15,   16,    8,    8,   17,    8,   18,
        8,   19,    8,   20,   21,   22,   23,    8,   24,    8,
        8,    8,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[25] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[195] =
    {   0,
        0,    0,  349,    0,   23,   27,   34,   26,  331,   28,
       27,   33,   15,    0,  350,   50,   53,   54,  330,   33,
       49,   46,   48,   45,   51,   53,   55,   72,   69,  336,
       60,   74,   65,   67,   79,   70,   73,  328,  320,   76,
       88,   94,   95,  337,   96,  336,  100,   88,   96,  101,
      332,  104,  334,  118,  333,  103,  122,  126,    0,  111,
      128,  123,  118,  133,  322,  135,  139,  138,  331,  145,
      330,  149,  140,  150,  169,  154,  317,  328,  159,  327,
      168,  156,  173,  172,  175,    0,  179,  181,    0,  183,
      201,  190,  326,  185,  325,  191,  311,  192,  194,  200,

      193,  207,  210,  319,  211,  318,  212,  214,  304,  213,
      219,  220,  150,  302,  301,  215,  302,  227,  216,  222,
      221,  314,  313,  235,    0,  236,  237,  239,  240,  305,
      304,  242,    0,  241,  243,  245,  247,  301,  300,  244,
      248,  249,  254,  311,  297,  296,  255,  259,  308,  262,
      307,  306,  288,  287,  264,  266,  303,  302,  301,  284,
      283,  267,  298,  297,  296,    0,    0,  295,  294,  293,
        0,    0,  292,  291,  350,  295,  289,  294,  293,  292,
      291,  285,  284,  282,  280,  279,  278,  277,  275,  274,
      166,  146,  118,   47

    } ;

static yyconst flex_int16_t yy_def[195] =
    {   0,
      175,    1,  175,  176,  177,  178,  178,    7,    7,    7,
        7,    7,    7,  176,  175,  175,  177,  176,    7,  176,
        7,    7,    7,    7,    7,    7,    7,  175,  176,  176,
        7,    7,    7,    7,  179,    7,    7,    7,  176,    7,
      180,    7,    7,  179,  179,  179,  179,    7,    7,    7,
      176,    7,  180,  180,  180,  180,  181,  176,  176,  179,
      179,    7,    7,    7,  176,  182,  180,  180,  181,  181,
      181,  181,  179,  183,  184,  185,  176,  182,  182,  182,
      182,  180,  181,  181,  179,  183,  183,  183,  186,  186,
      184,  186,  185,  185,  185,  185,  176,  182,  182,  180,

      181,  179,  183,  183,  186,  186,  185,  185,  176,  182,
      180,  181,  179,  183,  186,  185,  176,  182,  180,  181,
      179,  183,  186,  185,  187,  182,  180,  181,  179,  183,
      186,  185,  187,  182,  180,  181,  179,  183,  186,  185,
      182,  180,  181,  188,  183,  186,  185,  182,  189,  181,
      188,  188,  183,  186,  185,  182,  189,  189,  190,  183,
      186,  185,  191,  190,  190,  192,  193,  194,  191,  191,
      192,  193,  194,  194,    0,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175

    } ;

static yyconst flex_int16_t yy_nxt[375] =
    {   0,
        4,    4,    5,    4,    4,    4,    4,    6,    6,    6,
        7,    8,    9,    6,    6,   10,    6,    6,   11,   12,
        6,    6,    6,   13,   16,   17,   16,   14,   14,   27,
       18,   19,   14,   20,   14,   14,   29,   18,   22,   14,
       20,   24,   19,   19,   19,   26,   25,  173,   35,   19,
       21,   28,   30,   28,   16,   17,   16,   18,   31,   32,
       20,   19,   19,   33,   19,   19,   36,   19,   34,   19,
       38,   19,   29,   28,   37,   28,   19,   41,   42,   43,
       40,   19,   45,   19,   46,   47,   19,   48,   30,   19,
       19,   54,   19,   55,   56,   49,   52,   57,   58,   45,

       59,   46,   47,   60,   19,   46,   67,   66,   55,   62,
       19,   19,   19,   64,   60,   63,   46,   19,  172,   61,
       19,   54,   68,   55,   56,   70,   74,   71,   72,   58,
       61,   59,   20,   46,   19,   75,   76,   73,   79,   19,
       80,   81,   67,   55,   55,   46,  171,   82,   70,   19,
       71,   72,   83,   87,   71,   46,   88,   94,   68,   95,
       96,   55,   79,   85,   80,   81,  169,  121,   84,   89,
       89,   98,   90,   80,   89,   92,   83,   71,   71,  100,
       46,  101,   87,  102,  103,   88,   90,   99,   94,   92,
       95,   96,   84,  105,  107,   98,   95,   80,   71,   80,

      104,   89,   89,  110,   90,   55,   89,   92,  111,  106,
      108,   99,   46,  103,  105,  107,  112,   95,   80,   95,
       95,   55,  113,  116,   55,   71,   46,   71,  120,  104,
      106,  108,   80,  127,  119,  126,  118,  128,  124,  129,
       95,   80,   55,  132,   71,   46,   80,   95,   55,   95,
       71,  134,   46,   80,   55,  135,  136,  140,  141,   71,
       95,  147,  137,  143,   80,  142,  148,   71,  144,   95,
      149,   80,   95,  155,  164,  157,  150,  151,  133,   89,
       93,  156,   91,  159,   86,   78,  162,  163,  168,   15,
       15,   69,   53,   44,   19,   14,  174,  174,  170,  170,

      174,  165,  165,  170,  167,  166,  165,  158,  158,  161,
      160,  152,  152,  158,  154,  153,  152,  146,  145,  139,
      138,  131,  130,  125,  123,  122,  117,  115,  114,  109,
       95,   95,   80,   80,   97,   71,   71,   77,   55,   55,
       65,   46,   46,   51,   50,   39,   19,   23,  175,    3,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175
    } ;

static yyconst flex_int16_t yy_chk[375] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    5,    6,    6,   13,
        6,   13,    6,    6,    7,    7,   20,    7,    8,    7,
        7,   10,    8,   11,   10,   12,   11,  194,   24,   12,
        7,   16,   20,   16,   17,   17,   17,   18,   21,   22,
       18,   24,   22,   23,   23,   21,   25,   25,   23,   26,
       27,   27,   29,   28,   26,   28,   31,   32,   33,   34,
       31,   33,   35,   34,   35,   35,   36,   36,   29,   37,
       32,   41,   40,   41,   41,   37,   40,   42,   43,   45,

       43,   45,   45,   47,   48,   47,   56,   52,   56,   48,
       42,   43,   49,   50,   60,   49,   60,   50,  193,   47,
       52,   54,   56,   54,   54,   57,   62,   57,   57,   58,
       60,   58,   58,   61,   63,   63,   64,   61,   66,   62,
       66,   66,   67,   68,   67,   73,  192,   68,   70,   64,
       70,   70,   72,   74,   72,  113,   74,   76,   67,   76,
       76,   82,   79,   73,   79,   79,  191,  113,   72,   75,
       75,   81,   75,   81,   75,   75,   83,   84,   83,   82,
       85,   84,   87,   85,   88,   87,   90,   81,   94,   90,
       94,   94,   83,   92,   96,   98,   96,   98,  101,   99,

       88,   91,   91,   99,   91,  100,   91,   91,  100,   92,
       96,   98,  102,  103,  105,  107,  101,  107,  110,  108,
      116,  119,  102,  108,  111,  112,  121,  120,  112,  103,
      105,  107,  118,  119,  111,  118,  110,  120,  116,  121,
      124,  126,  127,  124,  128,  129,  134,  132,  135,  140,
      136,  126,  137,  141,  142,  127,  128,  132,  134,  143,
      147,  140,  129,  136,  148,  135,  141,  150,  137,  155,
      142,  156,  162,  147,  190,  189,  143,  188,  187,  186,
      185,  148,  184,  150,  183,  182,  155,  156,  162,  177,
      177,  181,  180,  179,  178,  176,  174,  173,  170,  169,

      168,  165,  164,  163,  161,  160,  159,  158,  157,  154,
      153,  152,  151,  149,  146,  145,  144,  139,  138,  131,
      130,  123,  122,  117,  115,  114,  109,  106,  104,   97,
       95,   93,   80,   78,   77,   71,   69,   65,   55,   53,
       51,   46,   44,   39,   38,   30,   19,    9,    3,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  175,  175,  175,  175,  175,
      175,  175,  175,  175
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int xx_flex_debug;
int xx_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *xxtext;
#line 1 "pythontocpp.l"
#line 2 "pythontocpp.l"
	#include<stdio.h>
	#include<stdlib.h>
	#include<string.h>
	#include"struct_table.h"
	int i=0;
	int j=0;
	int inClass = 0;
	char current_class_name[40];
	char current_block_spacing[100];
	char raw_input_string[100];	
	char iden[50];	
	struct node
	{
		char spacing[100];
	};
	struct stack
	{
		struct node arr[100];
		int top;
	}spacing_stack;
	void push(struct stack *the_stack, char* spacing)
	{
		the_stack->top++;
		strcpy(the_stack->arr[the_stack->top].spacing,spacing);		
	}
	void pop(struct stack *the_stack)
	{
		if(the_stack->top != -1)		
			the_stack->top--;
	}
	void quotes_check(char* xxtext)
	{
		int i=0,j=0;
		for(i=0;i<xxleng;i++)
		{
			if(xxtext[i] == '\'')
			{
				j=i+1;
				while(xxtext[j] != '\'')
					j++;
				if(j != i+2)
				{
					if(j != i+3 || (j == i+3 && xxtext[i+1] != '\\'))
					{
						xxtext[i] = '\"';
						xxtext[j] = '\"';
					}
				}
				i = j+1;
			}
			else if(xxtext[i] == '\"')
			{
				j=i+1;
				while(xxtext[j] != '\"')
					j++;
				if(j == i+2)
				{
					xxtext[i] = '\'';
					xxtext[j] = '\'';
				}
				i = j+1;
			}
		}
	}
	void write_arguments(char* xxtext,int start,int end_bracket)
	{
		int i;
		quotes_check(xxtext);
		for(i=start;i<xxleng;i++)
		{
			if (xxtext[i] == ':')
			{
				if(end_bracket)
					fprintf(xxout,")");
				fprintf(xxout,"%s{",current_block_spacing);
				break;
			}
			fprintf(xxout,"%c",xxtext[i]);
		}
	}
	char* replace_substring(char* str, char* original_sub, char* replace_sub)
	{
	    	char *buffer = (char*)malloc(4096*sizeof(char));
	    	char *p;
	     
	    	if(!(p = strstr(str, original_sub)))
	    	return str;
	     
	    	strncpy(buffer, str, p-str);
	    	buffer[p-str] = '\0';
	     
	    	sprintf(buffer+(p-str), "%s%s", replace_sub, p+strlen(original_sub));
	     	
		if (strstr(buffer, original_sub))
			buffer = replace_substring(buffer,original_sub,replace_sub);
		
	    	return buffer;
	}
	void remove_substring(char* str,char* substring)
	{
		size_t length = strlen(substring);
    		while((str = strstr(str, substring)))
		{
			memmove(str, str + length, 1 + strlen(str + length));
		}
	}
	void remove_self(char* xxtext)
	{
		remove_substring(xxtext,"self,");
		remove_substring(xxtext,"self");
	}
#line 731 "lex.xx.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int xxlex_destroy (void );

int xxget_debug (void );

void xxset_debug (int debug_flag  );

YY_EXTRA_TYPE xxget_extra (void );

void xxset_extra (YY_EXTRA_TYPE user_defined  );

FILE *xxget_in (void );

void xxset_in  (FILE * in_str  );

FILE *xxget_out (void );

void xxset_out  (FILE * out_str  );

int xxget_leng (void );

char *xxget_text (void );

int xxget_lineno (void );

void xxset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int xxwrap (void );
#else
extern int xxwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( xxtext, xxleng, 1, xxout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( xxin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( xxin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, xxin))==0 && ferror(xxin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(xxin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int xxlex (void);

#define YY_DECL int xxlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after xxtext and xxleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 115 "pythontocpp.l"

#line 920 "lex.xx.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! xxin )
			xxin = stdin;

		if ( ! xxout )
			xxout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			xxensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				xx_create_buffer(xxin,YY_BUF_SIZE );
		}

		xx_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of xxtext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 176 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 350 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 116 "pythontocpp.l"
{
	if(strcmp(xxtext,current_block_spacing) != 0)
	{
		if(strlen(current_block_spacing) < strlen(xxtext))
		{
			push(&spacing_stack,xxtext);
			strcpy(current_block_spacing,xxtext);
		}
		else
		{			
			pop(&spacing_stack);
			strcpy(current_block_spacing,spacing_stack.arr[spacing_stack.top].spacing);
			fprintf(xxout,"%s}",current_block_spacing);
		}
	}
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 132 "pythontocpp.l"
{
	pop(&spacing_stack);
	while(spacing_stack.top != -1)
	{
		strcpy(current_block_spacing,spacing_stack.arr[spacing_stack.top].spacing);
		fprintf(xxout,"%s}",current_block_spacing);
		pop(&spacing_stack);
	}
	fprintf(xxout,"\n");
	inClass = 0;
	strcpy(current_block_spacing,"");
	strcpy(current_class_name,"");
	yyless(1);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 146 "pythontocpp.l"
{
	xxtext = replace_substring(xxtext,"self.","this->");
	if (strstr(xxtext,"__name__") && strstr(xxtext,"__main__"))
	{
		fprintf(xxout,"int main()\n{");
	}
	else
	{
		fprintf(xxout,"%sif(",current_block_spacing);
		write_arguments(xxtext,3,1);
	}
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 158 "pythontocpp.l"
{
	xxtext = replace_substring(xxtext,"self.","this->");
	fprintf(xxout,"%selse if(",current_block_spacing);
	write_arguments(xxtext,5,1);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 163 "pythontocpp.l"
{
	xxtext = replace_substring(xxtext,"self.","this->");
	fprintf(xxout,"%selse",current_block_spacing);
	write_arguments(xxtext,5,0);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 168 "pythontocpp.l"
{
	xxtext = replace_substring(xxtext,"self.","this->");
	fprintf(xxout,"%swhile(",current_block_spacing);
	write_arguments(xxtext,6,1);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 173 "pythontocpp.l"
{
	xxtext = replace_substring(xxtext,"self.","this->");
	iden[0] = '\0';	
	fprintf(xxout,"%scout << ",current_block_spacing);
	i = 0;
	j = 0;
	for(i=6;i<strlen(xxtext);i++)
	{
		if(xxtext[i] == '+' || xxtext[i] == ',')
		{
			iden[j] = '\0';
			fprintf(xxout,"%s << ",iden);
			iden[0] = '\0';
			j = 0;
		}
		else if(xxtext[i] != ' ')
		{
			iden[j] = xxtext[i];
			j++;
		}
	}
	iden[j] = '\0';
	fprintf(xxout,"%s;",iden);
	iden[0] = '\0';
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 198 "pythontocpp.l"
{
	xxtext = replace_substring(xxtext,"self.","this->");
	fprintf(xxout,"%s%s;",current_block_spacing,xxtext);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 202 "pythontocpp.l"
{
	xxtext = replace_substring(xxtext,"self.","this->");
	i = 0;
	j = 0;	
	iden[0] = '\0';
	raw_input_string[0] = '\0';
	while(xxtext[i] != ' ')
	{
		iden[i] = xxtext[i];
		i++;
	}
	iden[i] = '\0';
	while(xxtext[i] != '(')
		i++;
	i++;
	while(xxtext[i] == ' ')
		i++;
	if(xxtext[i] == '\"' || xxtext[i] == '\'')
	{
		raw_input_string[j] = '\"';
		i++;
		j++; 
		while(xxtext[i] != '\"' && xxtext[i] != '\'')
		{
			raw_input_string[j] = xxtext[i];
			j++;
			i++;
		}
		raw_input_string[j] = '\"';
		raw_input_string[j+1] = '\0';
		fprintf(xxout,"%scout << %s;",current_block_spacing,raw_input_string);	
	}
	fprintf(xxout,"%scin >> %s;",current_block_spacing,iden);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 236 "pythontocpp.l"
{
	xxtext = replace_substring(xxtext,"self.","this->");
	fprintf(xxout,"class ");
	i = 6;
	j = 0;
	inClass = 1;
	while(xxtext[i] != '(')
	{
		fprintf(xxout,"%c",xxtext[i]);
		current_class_name[i-6] = xxtext[i];		
		i++;
	}
	current_class_name[i-6] = '\0';
	i++;
	while(xxtext[i] == ' ')
		i++;
	while(xxtext[i] != ')')
	{
		if(j == 0)
		{	
			fprintf(xxout," : public %c",xxtext[i]);
			j = 1;
		}		
		else
		{
			if(xxtext[i] == ',')
				fprintf(xxout,", public ");
			else
				fprintf(xxout,"%c",xxtext[i]);
		}
		i++;
	}
	fprintf(xxout,"\n{");
	push(&spacing_stack,"\n");
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 271 "pythontocpp.l"
{
	remove_self(xxtext);
	if(inClass == 1)
	{
		if(strstr(xxtext,"__init__"))
		{
			xxtext = replace_substring(xxtext,"__init__",current_class_name);
			fprintf(xxout,"%s",current_block_spacing);
		}
		else
		{
			fprintf(xxout,"%s_____ ",current_block_spacing);
		}
	}
	else
	{
		fprintf(xxout,"%s_____ ",current_block_spacing);
	}	
	if(inClass != 1)
	{
		strcat(current_block_spacing,"\n");		
		push(&spacing_stack,current_block_spacing);
	}
	write_arguments(xxtext,4,0);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 296 "pythontocpp.l"
{
	xxtext = replace_substring(xxtext,"self.","this->");
	quotes_check(xxtext);
	fprintf(xxout,"%s%s;",current_block_spacing,xxtext);
}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 301 "pythontocpp.l"
{}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 302 "pythontocpp.l"
ECHO;
	YY_BREAK
#line 1249 "lex.xx.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed xxin at a new source and called
			 * xxlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = xxin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( xxwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * xxtext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of xxlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					xxrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			xxrestart(xxin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) xxrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 176 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 176 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 175);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up xxtext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					xxrestart(xxin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( xxwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve xxtext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void xxrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        xxensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            xx_create_buffer(xxin,YY_BUF_SIZE );
	}

	xx_init_buffer(YY_CURRENT_BUFFER,input_file );
	xx_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void xx_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		xxpop_buffer_state();
	 *		xxpush_buffer_state(new_buffer);
     */
	xxensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	xx_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (xxwrap()) processing, but the only time this flag
	 * is looked at is after xxwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void xx_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	xxin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE xx_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) xxalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in xx_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) xxalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in xx_create_buffer()" );

	b->yy_is_our_buffer = 1;

	xx_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with xx_create_buffer()
 * 
 */
    void xx_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		xxfree((void *) b->yy_ch_buf  );

	xxfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a xxrestart() or at EOF.
 */
    static void xx_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	xx_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then xx_init_buffer was _probably_
     * called from xxrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void xx_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		xx_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void xxpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	xxensure_buffer_stack();

	/* This block is copied from xx_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from xx_switch_to_buffer. */
	xx_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void xxpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	xx_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		xx_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void xxensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)xxalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in xxensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)xxrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in xxensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE xx_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) xxalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in xx_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	xx_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to xxlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       xx_scan_bytes() instead.
 */
YY_BUFFER_STATE xx_scan_string (yyconst char * yystr )
{
    
	return xx_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to xxlex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE xx_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) xxalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in xx_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = xx_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in xx_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up xxtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		xxtext[xxleng] = (yy_hold_char); \
		(yy_c_buf_p) = xxtext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		xxleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int xxget_lineno  (void)
{
        
    return xxlineno;
}

/** Get the input stream.
 * 
 */
FILE *xxget_in  (void)
{
        return xxin;
}

/** Get the output stream.
 * 
 */
FILE *xxget_out  (void)
{
        return xxout;
}

/** Get the length of the current token.
 * 
 */
int xxget_leng  (void)
{
        return xxleng;
}

/** Get the current token.
 * 
 */

char *xxget_text  (void)
{
        return xxtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void xxset_lineno (int  line_number )
{
    
    xxlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see xx_switch_to_buffer
 */
void xxset_in (FILE *  in_str )
{
        xxin = in_str ;
}

void xxset_out (FILE *  out_str )
{
        xxout = out_str ;
}

int xxget_debug  (void)
{
        return xx_flex_debug;
}

void xxset_debug (int  bdebug )
{
        xx_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from xxlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    xxin = stdin;
    xxout = stdout;
#else
    xxin = (FILE *) 0;
    xxout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * xxlex_init()
     */
    return 0;
}

/* xxlex_destroy is for both reentrant and non-reentrant scanners. */
int xxlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		xx_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		xxpop_buffer_state();
	}

	/* Destroy the stack itself. */
	xxfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * xxlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *xxalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *xxrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void xxfree (void * ptr )
{
	free( (char *) ptr );	/* see xxrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 302 "pythontocpp.l"


main()
{
	spacing_stack.top = -1;
	xxin = fopen("./Python Codes/test_code_1.py","r");
	xxout = fopen("./Cpp Codes/cpp_code_1.cpp","w");
	fprintf(xxout,"#include<iostream>\n#include<stdio.h>\nusing namespace std;\n\n");
	xxlex();
	fprintf(xxout,"\n\treturn 0;\n}");
}
int xxwrap()
{
	return 1;
}

